### ISSUE TITLE
add test step

### ISSUE THREAD

**Issue by inliniac** [mrash/afl-cov#16]
When afl starts, it first confirms if the command it's about to fuzz even makes sense by running the test case. afl-cov should do something similar.

I had an issue where due to some error on my side, the instance that was being run to get the coverage failed even though the afl ran instance succeeded. Took me a long time to realize this :)

**Comment by mrash** [comment]
Thanks for the suggestion - will implement this.

**Comment by mrash** [comment]
afl-cov now writes the output of the first text case execution to the cov/afl-cov.log file. Because afl-cov needs the first AFL_FILE to be derived from the first AFL test case, it can't really execute the targeted binary until this test case is imported from the AFL fuzzing run. Also, afl-cov probably shouldn't exit() if the exit status of this command indicates an error condition since this is usually expected with AFL test case input anyway. I'll bet AFL itself is doing a check to see if the binary crashed or hangs for that initial check. If you happen to have the error details it might help me make sure this is probably handled. In the meantime, I'm hoping that taking a look at command output from the afl-cov.log will help.

**Comment by mrash** [comment]
I've added a check to ensure there is a an executable binary within the --coverage-cmd, and this check is done before any AFL test cases are needed. This would at least catch some problems where the binary path is not there or mistyped, etc. Please re-open this issue if more details come to light.
