### ISSUE TITLE
 No such file or directory:"afl_out/cov/lcov/afl_out/id:000001,src:000000,op:flip1,pos:0,+cov.lcov_info_final'

### ISSUE THREAD

**Issue by willsheil** [mrash/afl-cov#23]
Hi,I run afl-cov on ubuntu 14.04,but it reported that  lcov_info_final does't exist..
AFL test case: id:000001,src:000000,op:flip1,pos:0,+cov (1 / 273), cycle: 0
Traceback (most recent call last):
  File "/usr/local/share/afl-cov/afl-cov", line 1066, in <module>
    sys.exit(main())
  File "/usr/local/share/afl-cov/afl-cov", line 77, in main
    return not process_afl_test_cases(cargs)
  File "/usr/local/share/afl-cov/afl-cov", line 174, in process_afl_test_cases
    f, cov, cargs)
  File "/usr/local/share/afl-cov/afl-cov", line 261, in coverage_diff
    new_cov = extract_coverage(cp['lcov_info_final'], cargs)
  File "/usr/local/share/afl-cov/afl-cov", line 416, in extract_coverage
    with open(lcov_file, 'r') as f:
IOError: [Errno 2] No such file or directory: '/root/workspace/afl_binutils/binutils-2.26/afl_out/cov/lcov/afl_out/id:000001,src:000000,op:flip1,pos:0,+cov.lcov_info_final'

**Comment by mrash** [comment]
Thanks for the bug report. I have had one other report of this, and I will get it fixed.

**Comment by thus** [comment]
@willsheil: Try running afl-cov with --verbose, and then run the lcov commands (from the verbose output) executed by afl-cov manually. I encountered the same error as you. In my case, it was because lcov didn't run correctly, since I didn't point to the correct code directory.

@mrash: It would probably be better if afl-cov checked the return values from the commands executed to see when they fail, and return the output to the user upon failure. This would have saved some debugging time :)

**Comment by mrash** [comment]
@thus Agreed, will do. Did you encounter this problem on Ubuntu 14.04 as well? Or a different OS?

**Comment by thus** [comment]
Great, thanks :)

Yeah, I encountered this on Ubuntu 14.04 (and on 12.04) as well. I also got the "same" problem before I installed lcov.

**Comment by bshastry** [comment]
Hi! I encountered the problem faced by OP. In my case, it turned out that afl-cov was picking up lcov from `/usr/bin/lcov` by default. Although afl-cov supports a `--lcov-path` option (that fixes this problem should one not have lcov located at /usr/bin), it is better to do something like `env lcov` or `LCOV=`which lcov` before invoking it.

**Comment by mrash** [comment]
I think this issue is an artifact of the targeted binary not actually being compiled with code coverage support ('-fprofile-arcs -ftest-coverage'). I've implemented an additional check for this that uses readelf in a94bec3e. If anyone has spare cycles, please try to see if this works.

**Comment by mrash** [comment]
Ok, a new --validate-args switch has afl-cov detect whether the coverage command includes a binary with code coverage built-in. Here is an example from the test suite:

 ./afl/afl-cov-generator.sh --validate
+ CODE_DIR=./fwknop-codecov.git
+ AFL_COV=../afl-cov
+ AFL_TEST_CASES=./afl/e3ae6747/server-access.out
+ echo [+] server-access
[+] server-access
+ pwd
+ ../afl-cov -d ./afl/e3ae6747/server-access.out --coverage-cmd LD_LIBRARY_PATH=./fwknop-codecov.git/lib/.libs ./fwknop-codecov.git/server/.libs/fwknopd -c ./fwknop-codecov.git/test/conf/ipt_snat_fwknopd.conf -a AFL_FILE -O ./fwknop-codecov.git/test/conf/override_no_digest_tracking_fwknopd.conf -f -t --exit-parse-config -v -v -v -r /home/mbr/git/afl-cov.git/test --code-dir ./fwknop-codecov.git --validate
    Binary './fwknop-codecov.git/server/.libs/fwknopd' is compiled with code coverage support.
+ exit 0

**Comment by mrash** [comment]
This issue has been fixed in git master for the next release.
